/*****************************************************************
|
|   Neptune - Trust Anchors
|
|   This file is automatically generated by a script, do not edit!
|
| Copyright (c) 2002-2010, Axiomatic Systems, LLC.
| All rights reserved.
|
| Redistribution and use in source and binary forms, with or without
| modification, are permitted provided that the following conditions are met:
|     * Redistributions of source code must retain the above copyright
|       notice, this list of conditions and the following disclaimer.
|     * Redistributions in binary form must reproduce the above copyright
|       notice, this list of conditions and the following disclaimer in the
|       documentation and/or other materials provided with the distribution.
|     * Neither the name of Axiomatic Systems nor the
|       names of its contributors may be used to endorse or promote products
|       derived from this software without specific prior written permission.
|
| THIS SOFTWARE IS PROVIDED BY AXIOMATIC SYSTEMS ''AS IS'' AND ANY
| EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
| WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
| DISCLAIMED. IN NO EVENT SHALL AXIOMATIC SYSTEMS BE LIABLE FOR ANY
| DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
| (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
| LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND
| ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
| (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
| SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
|
 ****************************************************************/

 /* This file is automatically generated by GenTrustAnchorsTables.py, do not edit */

#include "NptTls.h"

extern const NPT_TlsTrustAnchorData NptTlsDefaultTrustAnchorsBase[139];

/* GlobalSign Root CA */
extern const unsigned int NptTlsTrustAnchor_Base_0000_Size;
extern const unsigned char NptTlsTrustAnchor_Base_0000_Data[];

/* GlobalSign Root CA - R2 */
extern const unsigned int NptTlsTrustAnchor_Base_0001_Size;
extern const unsigned char NptTlsTrustAnchor_Base_0001_Data[];

/* Verisign Class 3 Public Primary Certification Authority - G3 */
extern const unsigned int NptTlsTrustAnchor_Base_0002_Size;
extern const unsigned char NptTlsTrustAnchor_Base_0002_Data[];

/* Entrust.net Premium 2048 Secure Server CA */
extern const unsigned int NptTlsTrustAnchor_Base_0003_Size;
extern const unsigned char NptTlsTrustAnchor_Base_0003_Data[];

/* Baltimore CyberTrust Root */
extern const unsigned int NptTlsTrustAnchor_Base_0004_Size;
extern const unsigned char NptTlsTrustAnchor_Base_0004_Data[];

/* AddTrust External Root */
extern const unsigned int NptTlsTrustAnchor_Base_0005_Size;
extern const unsigned char NptTlsTrustAnchor_Base_0005_Data[];

/* Entrust Root Certification Authority */
extern const unsigned int NptTlsTrustAnchor_Base_0006_Size;
extern const unsigned char NptTlsTrustAnchor_Base_0006_Data[];

/* GeoTrust Global CA */
extern const unsigned int NptTlsTrustAnchor_Base_0007_Size;
extern const unsigned char NptTlsTrustAnchor_Base_0007_Data[];

/* GeoTrust Universal CA */
extern const unsigned int NptTlsTrustAnchor_Base_0008_Size;
extern const unsigned char NptTlsTrustAnchor_Base_0008_Data[];

/* GeoTrust Universal CA 2 */
extern const unsigned int NptTlsTrustAnchor_Base_0009_Size;
extern const unsigned char NptTlsTrustAnchor_Base_0009_Data[];

/* Comodo AAA Services root */
extern const unsigned int NptTlsTrustAnchor_Base_0010_Size;
extern const unsigned char NptTlsTrustAnchor_Base_0010_Data[];

/* QuoVadis Root CA */
extern const unsigned int NptTlsTrustAnchor_Base_0011_Size;
extern const unsigned char NptTlsTrustAnchor_Base_0011_Data[];

/* QuoVadis Root CA 2 */
extern const unsigned int NptTlsTrustAnchor_Base_0012_Size;
extern const unsigned char NptTlsTrustAnchor_Base_0012_Data[];

/* QuoVadis Root CA 3 */
extern const unsigned int NptTlsTrustAnchor_Base_0013_Size;
extern const unsigned char NptTlsTrustAnchor_Base_0013_Data[];

/* Security Communication Root CA */
extern const unsigned int NptTlsTrustAnchor_Base_0014_Size;
extern const unsigned char NptTlsTrustAnchor_Base_0014_Data[];

/* Sonera Class 2 Root CA */
extern const unsigned int NptTlsTrustAnchor_Base_0015_Size;
extern const unsigned char NptTlsTrustAnchor_Base_0015_Data[];

/* XRamp Global CA Root */
extern const unsigned int NptTlsTrustAnchor_Base_0016_Size;
extern const unsigned char NptTlsTrustAnchor_Base_0016_Data[];

/* Go Daddy Class 2 CA */
extern const unsigned int NptTlsTrustAnchor_Base_0017_Size;
extern const unsigned char NptTlsTrustAnchor_Base_0017_Data[];

/* Starfield Class 2 CA */
extern const unsigned int NptTlsTrustAnchor_Base_0018_Size;
extern const unsigned char NptTlsTrustAnchor_Base_0018_Data[];

/* Taiwan GRCA */
extern const unsigned int NptTlsTrustAnchor_Base_0019_Size;
extern const unsigned char NptTlsTrustAnchor_Base_0019_Data[];

/* DigiCert Assured ID Root CA */
extern const unsigned int NptTlsTrustAnchor_Base_0020_Size;
extern const unsigned char NptTlsTrustAnchor_Base_0020_Data[];

/* DigiCert Global Root CA */
extern const unsigned int NptTlsTrustAnchor_Base_0021_Size;
extern const unsigned char NptTlsTrustAnchor_Base_0021_Data[];

/* DigiCert High Assurance EV Root CA */
extern const unsigned int NptTlsTrustAnchor_Base_0022_Size;
extern const unsigned char NptTlsTrustAnchor_Base_0022_Data[];

/* DST Root CA X3 */
extern const unsigned int NptTlsTrustAnchor_Base_0023_Size;
extern const unsigned char NptTlsTrustAnchor_Base_0023_Data[];

/* SwissSign Gold CA - G2 */
extern const unsigned int NptTlsTrustAnchor_Base_0024_Size;
extern const unsigned char NptTlsTrustAnchor_Base_0024_Data[];

/* SwissSign Silver CA - G2 */
extern const unsigned int NptTlsTrustAnchor_Base_0025_Size;
extern const unsigned char NptTlsTrustAnchor_Base_0025_Data[];

/* GeoTrust Primary Certification Authority */
extern const unsigned int NptTlsTrustAnchor_Base_0026_Size;
extern const unsigned char NptTlsTrustAnchor_Base_0026_Data[];

/* thawte Primary Root CA */
extern const unsigned int NptTlsTrustAnchor_Base_0027_Size;
extern const unsigned char NptTlsTrustAnchor_Base_0027_Data[];

/* VeriSign Class 3 Public Primary Certification Authority - G5 */
extern const unsigned int NptTlsTrustAnchor_Base_0028_Size;
extern const unsigned char NptTlsTrustAnchor_Base_0028_Data[];

/* SecureTrust CA */
extern const unsigned int NptTlsTrustAnchor_Base_0029_Size;
extern const unsigned char NptTlsTrustAnchor_Base_0029_Data[];

/* Secure Global CA */
extern const unsigned int NptTlsTrustAnchor_Base_0030_Size;
extern const unsigned char NptTlsTrustAnchor_Base_0030_Data[];

/* COMODO Certification Authority */
extern const unsigned int NptTlsTrustAnchor_Base_0031_Size;
extern const unsigned char NptTlsTrustAnchor_Base_0031_Data[];

/* Network Solutions Certificate Authority */
extern const unsigned int NptTlsTrustAnchor_Base_0032_Size;
extern const unsigned char NptTlsTrustAnchor_Base_0032_Data[];

/* COMODO ECC Certification Authority */
extern const unsigned int NptTlsTrustAnchor_Base_0033_Size;
extern const unsigned char NptTlsTrustAnchor_Base_0033_Data[];

/* OISTE WISeKey Global Root GA CA */
extern const unsigned int NptTlsTrustAnchor_Base_0034_Size;
extern const unsigned char NptTlsTrustAnchor_Base_0034_Data[];

/* Certigna */
extern const unsigned int NptTlsTrustAnchor_Base_0035_Size;
extern const unsigned char NptTlsTrustAnchor_Base_0035_Data[];

/* Cybertrust Global Root */
extern const unsigned int NptTlsTrustAnchor_Base_0036_Size;
extern const unsigned char NptTlsTrustAnchor_Base_0036_Data[];

/* ePKI Root Certification Authority */
extern const unsigned int NptTlsTrustAnchor_Base_0037_Size;
extern const unsigned char NptTlsTrustAnchor_Base_0037_Data[];

/* certSIGN ROOT CA */
extern const unsigned int NptTlsTrustAnchor_Base_0038_Size;
extern const unsigned char NptTlsTrustAnchor_Base_0038_Data[];

/* GeoTrust Primary Certification Authority - G3 */
extern const unsigned int NptTlsTrustAnchor_Base_0039_Size;
extern const unsigned char NptTlsTrustAnchor_Base_0039_Data[];

/* thawte Primary Root CA - G2 */
extern const unsigned int NptTlsTrustAnchor_Base_0040_Size;
extern const unsigned char NptTlsTrustAnchor_Base_0040_Data[];

/* thawte Primary Root CA - G3 */
extern const unsigned int NptTlsTrustAnchor_Base_0041_Size;
extern const unsigned char NptTlsTrustAnchor_Base_0041_Data[];

/* GeoTrust Primary Certification Authority - G2 */
extern const unsigned int NptTlsTrustAnchor_Base_0042_Size;
extern const unsigned char NptTlsTrustAnchor_Base_0042_Data[];

/* VeriSign Universal Root Certification Authority */
extern const unsigned int NptTlsTrustAnchor_Base_0043_Size;
extern const unsigned char NptTlsTrustAnchor_Base_0043_Data[];

/* VeriSign Class 3 Public Primary Certification Authority - G4 */
extern const unsigned int NptTlsTrustAnchor_Base_0044_Size;
extern const unsigned char NptTlsTrustAnchor_Base_0044_Data[];

/* NetLock Arany (Class Gold) Főtanúsítvány */
extern const unsigned int NptTlsTrustAnchor_Base_0045_Size;
extern const unsigned char NptTlsTrustAnchor_Base_0045_Data[];

/* Staat der Nederlanden Root CA - G2 */
extern const unsigned int NptTlsTrustAnchor_Base_0046_Size;
extern const unsigned char NptTlsTrustAnchor_Base_0046_Data[];

/* Hongkong Post Root CA 1 */
extern const unsigned int NptTlsTrustAnchor_Base_0047_Size;
extern const unsigned char NptTlsTrustAnchor_Base_0047_Data[];

/* SecureSign RootCA11 */
extern const unsigned int NptTlsTrustAnchor_Base_0048_Size;
extern const unsigned char NptTlsTrustAnchor_Base_0048_Data[];

/* Microsec e-Szigno Root CA 2009 */
extern const unsigned int NptTlsTrustAnchor_Base_0049_Size;
extern const unsigned char NptTlsTrustAnchor_Base_0049_Data[];

/* GlobalSign Root CA - R3 */
extern const unsigned int NptTlsTrustAnchor_Base_0050_Size;
extern const unsigned char NptTlsTrustAnchor_Base_0050_Data[];

/* Autoridad de Certificacion Firmaprofesional CIF A62634068 */
extern const unsigned int NptTlsTrustAnchor_Base_0051_Size;
extern const unsigned char NptTlsTrustAnchor_Base_0051_Data[];

/* Izenpe.com */
extern const unsigned int NptTlsTrustAnchor_Base_0052_Size;
extern const unsigned char NptTlsTrustAnchor_Base_0052_Data[];

/* Chambers of Commerce Root - 2008 */
extern const unsigned int NptTlsTrustAnchor_Base_0053_Size;
extern const unsigned char NptTlsTrustAnchor_Base_0053_Data[];

/* Global Chambersign Root - 2008 */
extern const unsigned int NptTlsTrustAnchor_Base_0054_Size;
extern const unsigned char NptTlsTrustAnchor_Base_0054_Data[];

/* Go Daddy Root Certificate Authority - G2 */
extern const unsigned int NptTlsTrustAnchor_Base_0055_Size;
extern const unsigned char NptTlsTrustAnchor_Base_0055_Data[];

/* Starfield Root Certificate Authority - G2 */
extern const unsigned int NptTlsTrustAnchor_Base_0056_Size;
extern const unsigned char NptTlsTrustAnchor_Base_0056_Data[];

/* Starfield Services Root Certificate Authority - G2 */
extern const unsigned int NptTlsTrustAnchor_Base_0057_Size;
extern const unsigned char NptTlsTrustAnchor_Base_0057_Data[];

/* AffirmTrust Commercial */
extern const unsigned int NptTlsTrustAnchor_Base_0058_Size;
extern const unsigned char NptTlsTrustAnchor_Base_0058_Data[];

/* AffirmTrust Networking */
extern const unsigned int NptTlsTrustAnchor_Base_0059_Size;
extern const unsigned char NptTlsTrustAnchor_Base_0059_Data[];

/* AffirmTrust Premium */
extern const unsigned int NptTlsTrustAnchor_Base_0060_Size;
extern const unsigned char NptTlsTrustAnchor_Base_0060_Data[];

/* AffirmTrust Premium ECC */
extern const unsigned int NptTlsTrustAnchor_Base_0061_Size;
extern const unsigned char NptTlsTrustAnchor_Base_0061_Data[];

/* Certum Trusted Network CA */
extern const unsigned int NptTlsTrustAnchor_Base_0062_Size;
extern const unsigned char NptTlsTrustAnchor_Base_0062_Data[];

/* TWCA Root Certification Authority */
extern const unsigned int NptTlsTrustAnchor_Base_0063_Size;
extern const unsigned char NptTlsTrustAnchor_Base_0063_Data[];

/* Security Communication RootCA2 */
extern const unsigned int NptTlsTrustAnchor_Base_0064_Size;
extern const unsigned char NptTlsTrustAnchor_Base_0064_Data[];

/* EC-ACC */
extern const unsigned int NptTlsTrustAnchor_Base_0065_Size;
extern const unsigned char NptTlsTrustAnchor_Base_0065_Data[];

/* Hellenic Academic and Research Institutions RootCA 2011 */
extern const unsigned int NptTlsTrustAnchor_Base_0066_Size;
extern const unsigned char NptTlsTrustAnchor_Base_0066_Data[];

/* Actalis Authentication Root CA */
extern const unsigned int NptTlsTrustAnchor_Base_0067_Size;
extern const unsigned char NptTlsTrustAnchor_Base_0067_Data[];

/* Trustis FPS Root CA */
extern const unsigned int NptTlsTrustAnchor_Base_0068_Size;
extern const unsigned char NptTlsTrustAnchor_Base_0068_Data[];

/* Buypass Class 2 Root CA */
extern const unsigned int NptTlsTrustAnchor_Base_0069_Size;
extern const unsigned char NptTlsTrustAnchor_Base_0069_Data[];

/* Buypass Class 3 Root CA */
extern const unsigned int NptTlsTrustAnchor_Base_0070_Size;
extern const unsigned char NptTlsTrustAnchor_Base_0070_Data[];

/* T-TeleSec GlobalRoot Class 3 */
extern const unsigned int NptTlsTrustAnchor_Base_0071_Size;
extern const unsigned char NptTlsTrustAnchor_Base_0071_Data[];

/* EE Certification Centre Root CA */
extern const unsigned int NptTlsTrustAnchor_Base_0072_Size;
extern const unsigned char NptTlsTrustAnchor_Base_0072_Data[];

/* D-TRUST Root Class 3 CA 2 2009 */
extern const unsigned int NptTlsTrustAnchor_Base_0073_Size;
extern const unsigned char NptTlsTrustAnchor_Base_0073_Data[];

/* D-TRUST Root Class 3 CA 2 EV 2009 */
extern const unsigned int NptTlsTrustAnchor_Base_0074_Size;
extern const unsigned char NptTlsTrustAnchor_Base_0074_Data[];

/* CA Disig Root R2 */
extern const unsigned int NptTlsTrustAnchor_Base_0075_Size;
extern const unsigned char NptTlsTrustAnchor_Base_0075_Data[];

/* ACCVRAIZ1 */
extern const unsigned int NptTlsTrustAnchor_Base_0076_Size;
extern const unsigned char NptTlsTrustAnchor_Base_0076_Data[];

/* TWCA Global Root CA */
extern const unsigned int NptTlsTrustAnchor_Base_0077_Size;
extern const unsigned char NptTlsTrustAnchor_Base_0077_Data[];

/* TeliaSonera Root CA v1 */
extern const unsigned int NptTlsTrustAnchor_Base_0078_Size;
extern const unsigned char NptTlsTrustAnchor_Base_0078_Data[];

/* E-Tugra Certification Authority */
extern const unsigned int NptTlsTrustAnchor_Base_0079_Size;
extern const unsigned char NptTlsTrustAnchor_Base_0079_Data[];

/* T-TeleSec GlobalRoot Class 2 */
extern const unsigned int NptTlsTrustAnchor_Base_0080_Size;
extern const unsigned char NptTlsTrustAnchor_Base_0080_Data[];

/* Atos TrustedRoot 2011 */
extern const unsigned int NptTlsTrustAnchor_Base_0081_Size;
extern const unsigned char NptTlsTrustAnchor_Base_0081_Data[];

/* QuoVadis Root CA 1 G3 */
extern const unsigned int NptTlsTrustAnchor_Base_0082_Size;
extern const unsigned char NptTlsTrustAnchor_Base_0082_Data[];

/* QuoVadis Root CA 2 G3 */
extern const unsigned int NptTlsTrustAnchor_Base_0083_Size;
extern const unsigned char NptTlsTrustAnchor_Base_0083_Data[];

/* QuoVadis Root CA 3 G3 */
extern const unsigned int NptTlsTrustAnchor_Base_0084_Size;
extern const unsigned char NptTlsTrustAnchor_Base_0084_Data[];

/* DigiCert Assured ID Root G2 */
extern const unsigned int NptTlsTrustAnchor_Base_0085_Size;
extern const unsigned char NptTlsTrustAnchor_Base_0085_Data[];

/* DigiCert Assured ID Root G3 */
extern const unsigned int NptTlsTrustAnchor_Base_0086_Size;
extern const unsigned char NptTlsTrustAnchor_Base_0086_Data[];

/* DigiCert Global Root G2 */
extern const unsigned int NptTlsTrustAnchor_Base_0087_Size;
extern const unsigned char NptTlsTrustAnchor_Base_0087_Data[];

/* DigiCert Global Root G3 */
extern const unsigned int NptTlsTrustAnchor_Base_0088_Size;
extern const unsigned char NptTlsTrustAnchor_Base_0088_Data[];

/* DigiCert Trusted Root G4 */
extern const unsigned int NptTlsTrustAnchor_Base_0089_Size;
extern const unsigned char NptTlsTrustAnchor_Base_0089_Data[];

/* COMODO RSA Certification Authority */
extern const unsigned int NptTlsTrustAnchor_Base_0090_Size;
extern const unsigned char NptTlsTrustAnchor_Base_0090_Data[];

/* USERTrust RSA Certification Authority */
extern const unsigned int NptTlsTrustAnchor_Base_0091_Size;
extern const unsigned char NptTlsTrustAnchor_Base_0091_Data[];

/* USERTrust ECC Certification Authority */
extern const unsigned int NptTlsTrustAnchor_Base_0092_Size;
extern const unsigned char NptTlsTrustAnchor_Base_0092_Data[];

/* GlobalSign ECC Root CA - R4 */
extern const unsigned int NptTlsTrustAnchor_Base_0093_Size;
extern const unsigned char NptTlsTrustAnchor_Base_0093_Data[];

/* GlobalSign ECC Root CA - R5 */
extern const unsigned int NptTlsTrustAnchor_Base_0094_Size;
extern const unsigned char NptTlsTrustAnchor_Base_0094_Data[];

/* Staat der Nederlanden Root CA - G3 */
extern const unsigned int NptTlsTrustAnchor_Base_0095_Size;
extern const unsigned char NptTlsTrustAnchor_Base_0095_Data[];

/* Staat der Nederlanden EV Root CA */
extern const unsigned int NptTlsTrustAnchor_Base_0096_Size;
extern const unsigned char NptTlsTrustAnchor_Base_0096_Data[];

/* IdenTrust Commercial Root CA 1 */
extern const unsigned int NptTlsTrustAnchor_Base_0097_Size;
extern const unsigned char NptTlsTrustAnchor_Base_0097_Data[];

/* IdenTrust Public Sector Root CA 1 */
extern const unsigned int NptTlsTrustAnchor_Base_0098_Size;
extern const unsigned char NptTlsTrustAnchor_Base_0098_Data[];

/* Entrust Root Certification Authority - G2 */
extern const unsigned int NptTlsTrustAnchor_Base_0099_Size;
extern const unsigned char NptTlsTrustAnchor_Base_0099_Data[];

/* Entrust Root Certification Authority - EC1 */
extern const unsigned int NptTlsTrustAnchor_Base_0100_Size;
extern const unsigned char NptTlsTrustAnchor_Base_0100_Data[];

/* CFCA EV ROOT */
extern const unsigned int NptTlsTrustAnchor_Base_0101_Size;
extern const unsigned char NptTlsTrustAnchor_Base_0101_Data[];

/* OISTE WISeKey Global Root GB CA */
extern const unsigned int NptTlsTrustAnchor_Base_0102_Size;
extern const unsigned char NptTlsTrustAnchor_Base_0102_Data[];

/* SZAFIR ROOT CA2 */
extern const unsigned int NptTlsTrustAnchor_Base_0103_Size;
extern const unsigned char NptTlsTrustAnchor_Base_0103_Data[];

/* Certum Trusted Network CA 2 */
extern const unsigned int NptTlsTrustAnchor_Base_0104_Size;
extern const unsigned char NptTlsTrustAnchor_Base_0104_Data[];

/* Hellenic Academic and Research Institutions RootCA 2015 */
extern const unsigned int NptTlsTrustAnchor_Base_0105_Size;
extern const unsigned char NptTlsTrustAnchor_Base_0105_Data[];

/* Hellenic Academic and Research Institutions ECC RootCA 2015 */
extern const unsigned int NptTlsTrustAnchor_Base_0106_Size;
extern const unsigned char NptTlsTrustAnchor_Base_0106_Data[];

/* ISRG Root X1 */
extern const unsigned int NptTlsTrustAnchor_Base_0107_Size;
extern const unsigned char NptTlsTrustAnchor_Base_0107_Data[];

/* AC RAIZ FNMT-RCM */
extern const unsigned int NptTlsTrustAnchor_Base_0108_Size;
extern const unsigned char NptTlsTrustAnchor_Base_0108_Data[];

/* Amazon Root CA 1 */
extern const unsigned int NptTlsTrustAnchor_Base_0109_Size;
extern const unsigned char NptTlsTrustAnchor_Base_0109_Data[];

/* Amazon Root CA 2 */
extern const unsigned int NptTlsTrustAnchor_Base_0110_Size;
extern const unsigned char NptTlsTrustAnchor_Base_0110_Data[];

/* Amazon Root CA 3 */
extern const unsigned int NptTlsTrustAnchor_Base_0111_Size;
extern const unsigned char NptTlsTrustAnchor_Base_0111_Data[];

/* Amazon Root CA 4 */
extern const unsigned int NptTlsTrustAnchor_Base_0112_Size;
extern const unsigned char NptTlsTrustAnchor_Base_0112_Data[];

/* LuxTrust Global Root 2 */
extern const unsigned int NptTlsTrustAnchor_Base_0113_Size;
extern const unsigned char NptTlsTrustAnchor_Base_0113_Data[];

/* TUBITAK Kamu SM SSL Kok Sertifikasi - Surum 1 */
extern const unsigned int NptTlsTrustAnchor_Base_0114_Size;
extern const unsigned char NptTlsTrustAnchor_Base_0114_Data[];

/* GDCA TrustAUTH R5 ROOT */
extern const unsigned int NptTlsTrustAnchor_Base_0115_Size;
extern const unsigned char NptTlsTrustAnchor_Base_0115_Data[];

/* TrustCor RootCert CA-1 */
extern const unsigned int NptTlsTrustAnchor_Base_0116_Size;
extern const unsigned char NptTlsTrustAnchor_Base_0116_Data[];

/* TrustCor RootCert CA-2 */
extern const unsigned int NptTlsTrustAnchor_Base_0117_Size;
extern const unsigned char NptTlsTrustAnchor_Base_0117_Data[];

/* TrustCor ECA-1 */
extern const unsigned int NptTlsTrustAnchor_Base_0118_Size;
extern const unsigned char NptTlsTrustAnchor_Base_0118_Data[];

/* SSL.com Root Certification Authority RSA */
extern const unsigned int NptTlsTrustAnchor_Base_0119_Size;
extern const unsigned char NptTlsTrustAnchor_Base_0119_Data[];

/* SSL.com Root Certification Authority ECC */
extern const unsigned int NptTlsTrustAnchor_Base_0120_Size;
extern const unsigned char NptTlsTrustAnchor_Base_0120_Data[];

/* SSL.com EV Root Certification Authority RSA R2 */
extern const unsigned int NptTlsTrustAnchor_Base_0121_Size;
extern const unsigned char NptTlsTrustAnchor_Base_0121_Data[];

/* SSL.com EV Root Certification Authority ECC */
extern const unsigned int NptTlsTrustAnchor_Base_0122_Size;
extern const unsigned char NptTlsTrustAnchor_Base_0122_Data[];

/* GlobalSign Root CA - R6 */
extern const unsigned int NptTlsTrustAnchor_Base_0123_Size;
extern const unsigned char NptTlsTrustAnchor_Base_0123_Data[];

/* OISTE WISeKey Global Root GC CA */
extern const unsigned int NptTlsTrustAnchor_Base_0124_Size;
extern const unsigned char NptTlsTrustAnchor_Base_0124_Data[];

/* GTS Root R1 */
extern const unsigned int NptTlsTrustAnchor_Base_0125_Size;
extern const unsigned char NptTlsTrustAnchor_Base_0125_Data[];

/* GTS Root R2 */
extern const unsigned int NptTlsTrustAnchor_Base_0126_Size;
extern const unsigned char NptTlsTrustAnchor_Base_0126_Data[];

/* GTS Root R3 */
extern const unsigned int NptTlsTrustAnchor_Base_0127_Size;
extern const unsigned char NptTlsTrustAnchor_Base_0127_Data[];

/* GTS Root R4 */
extern const unsigned int NptTlsTrustAnchor_Base_0128_Size;
extern const unsigned char NptTlsTrustAnchor_Base_0128_Data[];

/* UCA Global G2 Root */
extern const unsigned int NptTlsTrustAnchor_Base_0129_Size;
extern const unsigned char NptTlsTrustAnchor_Base_0129_Data[];

/* UCA Extended Validation Root */
extern const unsigned int NptTlsTrustAnchor_Base_0130_Size;
extern const unsigned char NptTlsTrustAnchor_Base_0130_Data[];

/* Certigna Root CA */
extern const unsigned int NptTlsTrustAnchor_Base_0131_Size;
extern const unsigned char NptTlsTrustAnchor_Base_0131_Data[];

/* emSign Root CA - G1 */
extern const unsigned int NptTlsTrustAnchor_Base_0132_Size;
extern const unsigned char NptTlsTrustAnchor_Base_0132_Data[];

/* emSign ECC Root CA - G3 */
extern const unsigned int NptTlsTrustAnchor_Base_0133_Size;
extern const unsigned char NptTlsTrustAnchor_Base_0133_Data[];

/* emSign Root CA - C1 */
extern const unsigned int NptTlsTrustAnchor_Base_0134_Size;
extern const unsigned char NptTlsTrustAnchor_Base_0134_Data[];

/* emSign ECC Root CA - C3 */
extern const unsigned int NptTlsTrustAnchor_Base_0135_Size;
extern const unsigned char NptTlsTrustAnchor_Base_0135_Data[];

/* Hongkong Post Root CA 3 */
extern const unsigned int NptTlsTrustAnchor_Base_0136_Size;
extern const unsigned char NptTlsTrustAnchor_Base_0136_Data[];

/* Entrust Root Certification Authority - G4 */
extern const unsigned int NptTlsTrustAnchor_Base_0137_Size;
extern const unsigned char NptTlsTrustAnchor_Base_0137_Data[];

