/*****************************************************************
|
|   Neptune - Trust Anchors
|
|   This file is automatically generated by a script, do not edit!
|
| Copyright (c) 2002-2010, Axiomatic Systems, LLC.
| All rights reserved.
|
| Redistribution and use in source and binary forms, with or without
| modification, are permitted provided that the following conditions are met:
|     * Redistributions of source code must retain the above copyright
|       notice, this list of conditions and the following disclaimer.
|     * Redistributions in binary form must reproduce the above copyright
|       notice, this list of conditions and the following disclaimer in the
|       documentation and/or other materials provided with the distribution.
|     * Neither the name of Axiomatic Systems nor the
|       names of its contributors may be used to endorse or promote products
|       derived from this software without specific prior written permission.
|
| THIS SOFTWARE IS PROVIDED BY AXIOMATIC SYSTEMS ''AS IS'' AND ANY
| EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
| WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
| DISCLAIMED. IN NO EVENT SHALL AXIOMATIC SYSTEMS BE LIABLE FOR ANY
| DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
| (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
| LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND
| ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
| (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
| SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
|
 ****************************************************************/

 /* This file is automatically generated by GenTrustAnchorsTables.py, do not edit */

#include "NptTls.h"
#include "Base/NptTlsTrustAnchor_Base_0000.cpp" /* GlobalSign Root CA */
#include "Base/NptTlsTrustAnchor_Base_0001.cpp" /* GlobalSign Root CA - R2 */
#include "Base/NptTlsTrustAnchor_Base_0002.cpp" /* Verisign Class 3 Public Primary Certification Authority - G3 */
#include "Base/NptTlsTrustAnchor_Base_0003.cpp" /* Entrust.net Premium 2048 Secure Server CA */
#include "Base/NptTlsTrustAnchor_Base_0004.cpp" /* Baltimore CyberTrust Root */
#include "Base/NptTlsTrustAnchor_Base_0005.cpp" /* AddTrust External Root */
#include "Base/NptTlsTrustAnchor_Base_0006.cpp" /* Entrust Root Certification Authority */
#include "Base/NptTlsTrustAnchor_Base_0007.cpp" /* GeoTrust Global CA */
#include "Base/NptTlsTrustAnchor_Base_0008.cpp" /* GeoTrust Universal CA */
#include "Base/NptTlsTrustAnchor_Base_0009.cpp" /* GeoTrust Universal CA 2 */
#include "Base/NptTlsTrustAnchor_Base_0010.cpp" /* Comodo AAA Services root */
#include "Base/NptTlsTrustAnchor_Base_0011.cpp" /* QuoVadis Root CA */
#include "Base/NptTlsTrustAnchor_Base_0012.cpp" /* QuoVadis Root CA 2 */
#include "Base/NptTlsTrustAnchor_Base_0013.cpp" /* QuoVadis Root CA 3 */
#include "Base/NptTlsTrustAnchor_Base_0014.cpp" /* Security Communication Root CA */
#include "Base/NptTlsTrustAnchor_Base_0015.cpp" /* Sonera Class 2 Root CA */
#include "Base/NptTlsTrustAnchor_Base_0016.cpp" /* XRamp Global CA Root */
#include "Base/NptTlsTrustAnchor_Base_0017.cpp" /* Go Daddy Class 2 CA */
#include "Base/NptTlsTrustAnchor_Base_0018.cpp" /* Starfield Class 2 CA */
#include "Base/NptTlsTrustAnchor_Base_0019.cpp" /* Taiwan GRCA */
#include "Base/NptTlsTrustAnchor_Base_0020.cpp" /* DigiCert Assured ID Root CA */
#include "Base/NptTlsTrustAnchor_Base_0021.cpp" /* DigiCert Global Root CA */
#include "Base/NptTlsTrustAnchor_Base_0022.cpp" /* DigiCert High Assurance EV Root CA */
#include "Base/NptTlsTrustAnchor_Base_0023.cpp" /* DST Root CA X3 */
#include "Base/NptTlsTrustAnchor_Base_0024.cpp" /* SwissSign Gold CA - G2 */
#include "Base/NptTlsTrustAnchor_Base_0025.cpp" /* SwissSign Silver CA - G2 */
#include "Base/NptTlsTrustAnchor_Base_0026.cpp" /* GeoTrust Primary Certification Authority */
#include "Base/NptTlsTrustAnchor_Base_0027.cpp" /* thawte Primary Root CA */
#include "Base/NptTlsTrustAnchor_Base_0028.cpp" /* VeriSign Class 3 Public Primary Certification Authority - G5 */
#include "Base/NptTlsTrustAnchor_Base_0029.cpp" /* SecureTrust CA */
#include "Base/NptTlsTrustAnchor_Base_0030.cpp" /* Secure Global CA */
#include "Base/NptTlsTrustAnchor_Base_0031.cpp" /* COMODO Certification Authority */
#include "Base/NptTlsTrustAnchor_Base_0032.cpp" /* Network Solutions Certificate Authority */
#include "Base/NptTlsTrustAnchor_Base_0033.cpp" /* COMODO ECC Certification Authority */
#include "Base/NptTlsTrustAnchor_Base_0034.cpp" /* OISTE WISeKey Global Root GA CA */
#include "Base/NptTlsTrustAnchor_Base_0035.cpp" /* Certigna */
#include "Base/NptTlsTrustAnchor_Base_0036.cpp" /* Cybertrust Global Root */
#include "Base/NptTlsTrustAnchor_Base_0037.cpp" /* ePKI Root Certification Authority */
#include "Base/NptTlsTrustAnchor_Base_0038.cpp" /* certSIGN ROOT CA */
#include "Base/NptTlsTrustAnchor_Base_0039.cpp" /* GeoTrust Primary Certification Authority - G3 */
#include "Base/NptTlsTrustAnchor_Base_0040.cpp" /* thawte Primary Root CA - G2 */
#include "Base/NptTlsTrustAnchor_Base_0041.cpp" /* thawte Primary Root CA - G3 */
#include "Base/NptTlsTrustAnchor_Base_0042.cpp" /* GeoTrust Primary Certification Authority - G2 */
#include "Base/NptTlsTrustAnchor_Base_0043.cpp" /* VeriSign Universal Root Certification Authority */
#include "Base/NptTlsTrustAnchor_Base_0044.cpp" /* VeriSign Class 3 Public Primary Certification Authority - G4 */
#include "Base/NptTlsTrustAnchor_Base_0045.cpp" /* NetLock Arany (Class Gold) Főtanúsítvány */
#include "Base/NptTlsTrustAnchor_Base_0046.cpp" /* Staat der Nederlanden Root CA - G2 */
#include "Base/NptTlsTrustAnchor_Base_0047.cpp" /* Hongkong Post Root CA 1 */
#include "Base/NptTlsTrustAnchor_Base_0048.cpp" /* SecureSign RootCA11 */
#include "Base/NptTlsTrustAnchor_Base_0049.cpp" /* Microsec e-Szigno Root CA 2009 */
#include "Base/NptTlsTrustAnchor_Base_0050.cpp" /* GlobalSign Root CA - R3 */
#include "Base/NptTlsTrustAnchor_Base_0051.cpp" /* Autoridad de Certificacion Firmaprofesional CIF A62634068 */
#include "Base/NptTlsTrustAnchor_Base_0052.cpp" /* Izenpe.com */
#include "Base/NptTlsTrustAnchor_Base_0053.cpp" /* Chambers of Commerce Root - 2008 */
#include "Base/NptTlsTrustAnchor_Base_0054.cpp" /* Global Chambersign Root - 2008 */
#include "Base/NptTlsTrustAnchor_Base_0055.cpp" /* Go Daddy Root Certificate Authority - G2 */
#include "Base/NptTlsTrustAnchor_Base_0056.cpp" /* Starfield Root Certificate Authority - G2 */
#include "Base/NptTlsTrustAnchor_Base_0057.cpp" /* Starfield Services Root Certificate Authority - G2 */
#include "Base/NptTlsTrustAnchor_Base_0058.cpp" /* AffirmTrust Commercial */
#include "Base/NptTlsTrustAnchor_Base_0059.cpp" /* AffirmTrust Networking */
#include "Base/NptTlsTrustAnchor_Base_0060.cpp" /* AffirmTrust Premium */
#include "Base/NptTlsTrustAnchor_Base_0061.cpp" /* AffirmTrust Premium ECC */
#include "Base/NptTlsTrustAnchor_Base_0062.cpp" /* Certum Trusted Network CA */
#include "Base/NptTlsTrustAnchor_Base_0063.cpp" /* TWCA Root Certification Authority */
#include "Base/NptTlsTrustAnchor_Base_0064.cpp" /* Security Communication RootCA2 */
#include "Base/NptTlsTrustAnchor_Base_0065.cpp" /* EC-ACC */
#include "Base/NptTlsTrustAnchor_Base_0066.cpp" /* Hellenic Academic and Research Institutions RootCA 2011 */
#include "Base/NptTlsTrustAnchor_Base_0067.cpp" /* Actalis Authentication Root CA */
#include "Base/NptTlsTrustAnchor_Base_0068.cpp" /* Trustis FPS Root CA */
#include "Base/NptTlsTrustAnchor_Base_0069.cpp" /* Buypass Class 2 Root CA */
#include "Base/NptTlsTrustAnchor_Base_0070.cpp" /* Buypass Class 3 Root CA */
#include "Base/NptTlsTrustAnchor_Base_0071.cpp" /* T-TeleSec GlobalRoot Class 3 */
#include "Base/NptTlsTrustAnchor_Base_0072.cpp" /* EE Certification Centre Root CA */
#include "Base/NptTlsTrustAnchor_Base_0073.cpp" /* D-TRUST Root Class 3 CA 2 2009 */
#include "Base/NptTlsTrustAnchor_Base_0074.cpp" /* D-TRUST Root Class 3 CA 2 EV 2009 */
#include "Base/NptTlsTrustAnchor_Base_0075.cpp" /* CA Disig Root R2 */
#include "Base/NptTlsTrustAnchor_Base_0076.cpp" /* ACCVRAIZ1 */
#include "Base/NptTlsTrustAnchor_Base_0077.cpp" /* TWCA Global Root CA */
#include "Base/NptTlsTrustAnchor_Base_0078.cpp" /* TeliaSonera Root CA v1 */
#include "Base/NptTlsTrustAnchor_Base_0079.cpp" /* E-Tugra Certification Authority */
#include "Base/NptTlsTrustAnchor_Base_0080.cpp" /* T-TeleSec GlobalRoot Class 2 */
#include "Base/NptTlsTrustAnchor_Base_0081.cpp" /* Atos TrustedRoot 2011 */
#include "Base/NptTlsTrustAnchor_Base_0082.cpp" /* QuoVadis Root CA 1 G3 */
#include "Base/NptTlsTrustAnchor_Base_0083.cpp" /* QuoVadis Root CA 2 G3 */
#include "Base/NptTlsTrustAnchor_Base_0084.cpp" /* QuoVadis Root CA 3 G3 */
#include "Base/NptTlsTrustAnchor_Base_0085.cpp" /* DigiCert Assured ID Root G2 */
#include "Base/NptTlsTrustAnchor_Base_0086.cpp" /* DigiCert Assured ID Root G3 */
#include "Base/NptTlsTrustAnchor_Base_0087.cpp" /* DigiCert Global Root G2 */
#include "Base/NptTlsTrustAnchor_Base_0088.cpp" /* DigiCert Global Root G3 */
#include "Base/NptTlsTrustAnchor_Base_0089.cpp" /* DigiCert Trusted Root G4 */
#include "Base/NptTlsTrustAnchor_Base_0090.cpp" /* COMODO RSA Certification Authority */
#include "Base/NptTlsTrustAnchor_Base_0091.cpp" /* USERTrust RSA Certification Authority */
#include "Base/NptTlsTrustAnchor_Base_0092.cpp" /* USERTrust ECC Certification Authority */
#include "Base/NptTlsTrustAnchor_Base_0093.cpp" /* GlobalSign ECC Root CA - R4 */
#include "Base/NptTlsTrustAnchor_Base_0094.cpp" /* GlobalSign ECC Root CA - R5 */
#include "Base/NptTlsTrustAnchor_Base_0095.cpp" /* Staat der Nederlanden Root CA - G3 */
#include "Base/NptTlsTrustAnchor_Base_0096.cpp" /* Staat der Nederlanden EV Root CA */
#include "Base/NptTlsTrustAnchor_Base_0097.cpp" /* IdenTrust Commercial Root CA 1 */
#include "Base/NptTlsTrustAnchor_Base_0098.cpp" /* IdenTrust Public Sector Root CA 1 */
#include "Base/NptTlsTrustAnchor_Base_0099.cpp" /* Entrust Root Certification Authority - G2 */
#include "Base/NptTlsTrustAnchor_Base_0100.cpp" /* Entrust Root Certification Authority - EC1 */
#include "Base/NptTlsTrustAnchor_Base_0101.cpp" /* CFCA EV ROOT */
#include "Base/NptTlsTrustAnchor_Base_0102.cpp" /* OISTE WISeKey Global Root GB CA */
#include "Base/NptTlsTrustAnchor_Base_0103.cpp" /* SZAFIR ROOT CA2 */
#include "Base/NptTlsTrustAnchor_Base_0104.cpp" /* Certum Trusted Network CA 2 */
#include "Base/NptTlsTrustAnchor_Base_0105.cpp" /* Hellenic Academic and Research Institutions RootCA 2015 */
#include "Base/NptTlsTrustAnchor_Base_0106.cpp" /* Hellenic Academic and Research Institutions ECC RootCA 2015 */
#include "Base/NptTlsTrustAnchor_Base_0107.cpp" /* ISRG Root X1 */
#include "Base/NptTlsTrustAnchor_Base_0108.cpp" /* AC RAIZ FNMT-RCM */
#include "Base/NptTlsTrustAnchor_Base_0109.cpp" /* Amazon Root CA 1 */
#include "Base/NptTlsTrustAnchor_Base_0110.cpp" /* Amazon Root CA 2 */
#include "Base/NptTlsTrustAnchor_Base_0111.cpp" /* Amazon Root CA 3 */
#include "Base/NptTlsTrustAnchor_Base_0112.cpp" /* Amazon Root CA 4 */
#include "Base/NptTlsTrustAnchor_Base_0113.cpp" /* LuxTrust Global Root 2 */
#include "Base/NptTlsTrustAnchor_Base_0114.cpp" /* TUBITAK Kamu SM SSL Kok Sertifikasi - Surum 1 */
#include "Base/NptTlsTrustAnchor_Base_0115.cpp" /* GDCA TrustAUTH R5 ROOT */
#include "Base/NptTlsTrustAnchor_Base_0116.cpp" /* TrustCor RootCert CA-1 */
#include "Base/NptTlsTrustAnchor_Base_0117.cpp" /* TrustCor RootCert CA-2 */
#include "Base/NptTlsTrustAnchor_Base_0118.cpp" /* TrustCor ECA-1 */
#include "Base/NptTlsTrustAnchor_Base_0119.cpp" /* SSL.com Root Certification Authority RSA */
#include "Base/NptTlsTrustAnchor_Base_0120.cpp" /* SSL.com Root Certification Authority ECC */
#include "Base/NptTlsTrustAnchor_Base_0121.cpp" /* SSL.com EV Root Certification Authority RSA R2 */
#include "Base/NptTlsTrustAnchor_Base_0122.cpp" /* SSL.com EV Root Certification Authority ECC */
#include "Base/NptTlsTrustAnchor_Base_0123.cpp" /* GlobalSign Root CA - R6 */
#include "Base/NptTlsTrustAnchor_Base_0124.cpp" /* OISTE WISeKey Global Root GC CA */
#include "Base/NptTlsTrustAnchor_Base_0125.cpp" /* GTS Root R1 */
#include "Base/NptTlsTrustAnchor_Base_0126.cpp" /* GTS Root R2 */
#include "Base/NptTlsTrustAnchor_Base_0127.cpp" /* GTS Root R3 */
#include "Base/NptTlsTrustAnchor_Base_0128.cpp" /* GTS Root R4 */
#include "Base/NptTlsTrustAnchor_Base_0129.cpp" /* UCA Global G2 Root */
#include "Base/NptTlsTrustAnchor_Base_0130.cpp" /* UCA Extended Validation Root */
#include "Base/NptTlsTrustAnchor_Base_0131.cpp" /* Certigna Root CA */
#include "Base/NptTlsTrustAnchor_Base_0132.cpp" /* emSign Root CA - G1 */
#include "Base/NptTlsTrustAnchor_Base_0133.cpp" /* emSign ECC Root CA - G3 */
#include "Base/NptTlsTrustAnchor_Base_0134.cpp" /* emSign Root CA - C1 */
#include "Base/NptTlsTrustAnchor_Base_0135.cpp" /* emSign ECC Root CA - C3 */
#include "Base/NptTlsTrustAnchor_Base_0136.cpp" /* Hongkong Post Root CA 3 */
#include "Base/NptTlsTrustAnchor_Base_0137.cpp" /* Entrust Root Certification Authority - G4 */
/* total anchors size =153426 */

const NPT_TlsTrustAnchorData NptTlsDefaultTrustAnchorsBase[139] = {
    { NptTlsTrustAnchor_Base_0000_Data, NptTlsTrustAnchor_Base_0000_Size} /* GlobalSign Root CA */,
    { NptTlsTrustAnchor_Base_0001_Data, NptTlsTrustAnchor_Base_0001_Size} /* GlobalSign Root CA - R2 */,
    { NptTlsTrustAnchor_Base_0002_Data, NptTlsTrustAnchor_Base_0002_Size} /* Verisign Class 3 Public Primary Certification Authority - G3 */,
    { NptTlsTrustAnchor_Base_0003_Data, NptTlsTrustAnchor_Base_0003_Size} /* Entrust.net Premium 2048 Secure Server CA */,
    { NptTlsTrustAnchor_Base_0004_Data, NptTlsTrustAnchor_Base_0004_Size} /* Baltimore CyberTrust Root */,
    { NptTlsTrustAnchor_Base_0005_Data, NptTlsTrustAnchor_Base_0005_Size} /* AddTrust External Root */,
    { NptTlsTrustAnchor_Base_0006_Data, NptTlsTrustAnchor_Base_0006_Size} /* Entrust Root Certification Authority */,
    { NptTlsTrustAnchor_Base_0007_Data, NptTlsTrustAnchor_Base_0007_Size} /* GeoTrust Global CA */,
    { NptTlsTrustAnchor_Base_0008_Data, NptTlsTrustAnchor_Base_0008_Size} /* GeoTrust Universal CA */,
    { NptTlsTrustAnchor_Base_0009_Data, NptTlsTrustAnchor_Base_0009_Size} /* GeoTrust Universal CA 2 */,
    { NptTlsTrustAnchor_Base_0010_Data, NptTlsTrustAnchor_Base_0010_Size} /* Comodo AAA Services root */,
    { NptTlsTrustAnchor_Base_0011_Data, NptTlsTrustAnchor_Base_0011_Size} /* QuoVadis Root CA */,
    { NptTlsTrustAnchor_Base_0012_Data, NptTlsTrustAnchor_Base_0012_Size} /* QuoVadis Root CA 2 */,
    { NptTlsTrustAnchor_Base_0013_Data, NptTlsTrustAnchor_Base_0013_Size} /* QuoVadis Root CA 3 */,
    { NptTlsTrustAnchor_Base_0014_Data, NptTlsTrustAnchor_Base_0014_Size} /* Security Communication Root CA */,
    { NptTlsTrustAnchor_Base_0015_Data, NptTlsTrustAnchor_Base_0015_Size} /* Sonera Class 2 Root CA */,
    { NptTlsTrustAnchor_Base_0016_Data, NptTlsTrustAnchor_Base_0016_Size} /* XRamp Global CA Root */,
    { NptTlsTrustAnchor_Base_0017_Data, NptTlsTrustAnchor_Base_0017_Size} /* Go Daddy Class 2 CA */,
    { NptTlsTrustAnchor_Base_0018_Data, NptTlsTrustAnchor_Base_0018_Size} /* Starfield Class 2 CA */,
    { NptTlsTrustAnchor_Base_0019_Data, NptTlsTrustAnchor_Base_0019_Size} /* Taiwan GRCA */,
    { NptTlsTrustAnchor_Base_0020_Data, NptTlsTrustAnchor_Base_0020_Size} /* DigiCert Assured ID Root CA */,
    { NptTlsTrustAnchor_Base_0021_Data, NptTlsTrustAnchor_Base_0021_Size} /* DigiCert Global Root CA */,
    { NptTlsTrustAnchor_Base_0022_Data, NptTlsTrustAnchor_Base_0022_Size} /* DigiCert High Assurance EV Root CA */,
    { NptTlsTrustAnchor_Base_0023_Data, NptTlsTrustAnchor_Base_0023_Size} /* DST Root CA X3 */,
    { NptTlsTrustAnchor_Base_0024_Data, NptTlsTrustAnchor_Base_0024_Size} /* SwissSign Gold CA - G2 */,
    { NptTlsTrustAnchor_Base_0025_Data, NptTlsTrustAnchor_Base_0025_Size} /* SwissSign Silver CA - G2 */,
    { NptTlsTrustAnchor_Base_0026_Data, NptTlsTrustAnchor_Base_0026_Size} /* GeoTrust Primary Certification Authority */,
    { NptTlsTrustAnchor_Base_0027_Data, NptTlsTrustAnchor_Base_0027_Size} /* thawte Primary Root CA */,
    { NptTlsTrustAnchor_Base_0028_Data, NptTlsTrustAnchor_Base_0028_Size} /* VeriSign Class 3 Public Primary Certification Authority - G5 */,
    { NptTlsTrustAnchor_Base_0029_Data, NptTlsTrustAnchor_Base_0029_Size} /* SecureTrust CA */,
    { NptTlsTrustAnchor_Base_0030_Data, NptTlsTrustAnchor_Base_0030_Size} /* Secure Global CA */,
    { NptTlsTrustAnchor_Base_0031_Data, NptTlsTrustAnchor_Base_0031_Size} /* COMODO Certification Authority */,
    { NptTlsTrustAnchor_Base_0032_Data, NptTlsTrustAnchor_Base_0032_Size} /* Network Solutions Certificate Authority */,
    { NptTlsTrustAnchor_Base_0033_Data, NptTlsTrustAnchor_Base_0033_Size} /* COMODO ECC Certification Authority */,
    { NptTlsTrustAnchor_Base_0034_Data, NptTlsTrustAnchor_Base_0034_Size} /* OISTE WISeKey Global Root GA CA */,
    { NptTlsTrustAnchor_Base_0035_Data, NptTlsTrustAnchor_Base_0035_Size} /* Certigna */,
    { NptTlsTrustAnchor_Base_0036_Data, NptTlsTrustAnchor_Base_0036_Size} /* Cybertrust Global Root */,
    { NptTlsTrustAnchor_Base_0037_Data, NptTlsTrustAnchor_Base_0037_Size} /* ePKI Root Certification Authority */,
    { NptTlsTrustAnchor_Base_0038_Data, NptTlsTrustAnchor_Base_0038_Size} /* certSIGN ROOT CA */,
    { NptTlsTrustAnchor_Base_0039_Data, NptTlsTrustAnchor_Base_0039_Size} /* GeoTrust Primary Certification Authority - G3 */,
    { NptTlsTrustAnchor_Base_0040_Data, NptTlsTrustAnchor_Base_0040_Size} /* thawte Primary Root CA - G2 */,
    { NptTlsTrustAnchor_Base_0041_Data, NptTlsTrustAnchor_Base_0041_Size} /* thawte Primary Root CA - G3 */,
    { NptTlsTrustAnchor_Base_0042_Data, NptTlsTrustAnchor_Base_0042_Size} /* GeoTrust Primary Certification Authority - G2 */,
    { NptTlsTrustAnchor_Base_0043_Data, NptTlsTrustAnchor_Base_0043_Size} /* VeriSign Universal Root Certification Authority */,
    { NptTlsTrustAnchor_Base_0044_Data, NptTlsTrustAnchor_Base_0044_Size} /* VeriSign Class 3 Public Primary Certification Authority - G4 */,
    { NptTlsTrustAnchor_Base_0045_Data, NptTlsTrustAnchor_Base_0045_Size} /* NetLock Arany (Class Gold) Főtanúsítvány */,
    { NptTlsTrustAnchor_Base_0046_Data, NptTlsTrustAnchor_Base_0046_Size} /* Staat der Nederlanden Root CA - G2 */,
    { NptTlsTrustAnchor_Base_0047_Data, NptTlsTrustAnchor_Base_0047_Size} /* Hongkong Post Root CA 1 */,
    { NptTlsTrustAnchor_Base_0048_Data, NptTlsTrustAnchor_Base_0048_Size} /* SecureSign RootCA11 */,
    { NptTlsTrustAnchor_Base_0049_Data, NptTlsTrustAnchor_Base_0049_Size} /* Microsec e-Szigno Root CA 2009 */,
    { NptTlsTrustAnchor_Base_0050_Data, NptTlsTrustAnchor_Base_0050_Size} /* GlobalSign Root CA - R3 */,
    { NptTlsTrustAnchor_Base_0051_Data, NptTlsTrustAnchor_Base_0051_Size} /* Autoridad de Certificacion Firmaprofesional CIF A62634068 */,
    { NptTlsTrustAnchor_Base_0052_Data, NptTlsTrustAnchor_Base_0052_Size} /* Izenpe.com */,
    { NptTlsTrustAnchor_Base_0053_Data, NptTlsTrustAnchor_Base_0053_Size} /* Chambers of Commerce Root - 2008 */,
    { NptTlsTrustAnchor_Base_0054_Data, NptTlsTrustAnchor_Base_0054_Size} /* Global Chambersign Root - 2008 */,
    { NptTlsTrustAnchor_Base_0055_Data, NptTlsTrustAnchor_Base_0055_Size} /* Go Daddy Root Certificate Authority - G2 */,
    { NptTlsTrustAnchor_Base_0056_Data, NptTlsTrustAnchor_Base_0056_Size} /* Starfield Root Certificate Authority - G2 */,
    { NptTlsTrustAnchor_Base_0057_Data, NptTlsTrustAnchor_Base_0057_Size} /* Starfield Services Root Certificate Authority - G2 */,
    { NptTlsTrustAnchor_Base_0058_Data, NptTlsTrustAnchor_Base_0058_Size} /* AffirmTrust Commercial */,
    { NptTlsTrustAnchor_Base_0059_Data, NptTlsTrustAnchor_Base_0059_Size} /* AffirmTrust Networking */,
    { NptTlsTrustAnchor_Base_0060_Data, NptTlsTrustAnchor_Base_0060_Size} /* AffirmTrust Premium */,
    { NptTlsTrustAnchor_Base_0061_Data, NptTlsTrustAnchor_Base_0061_Size} /* AffirmTrust Premium ECC */,
    { NptTlsTrustAnchor_Base_0062_Data, NptTlsTrustAnchor_Base_0062_Size} /* Certum Trusted Network CA */,
    { NptTlsTrustAnchor_Base_0063_Data, NptTlsTrustAnchor_Base_0063_Size} /* TWCA Root Certification Authority */,
    { NptTlsTrustAnchor_Base_0064_Data, NptTlsTrustAnchor_Base_0064_Size} /* Security Communication RootCA2 */,
    { NptTlsTrustAnchor_Base_0065_Data, NptTlsTrustAnchor_Base_0065_Size} /* EC-ACC */,
    { NptTlsTrustAnchor_Base_0066_Data, NptTlsTrustAnchor_Base_0066_Size} /* Hellenic Academic and Research Institutions RootCA 2011 */,
    { NptTlsTrustAnchor_Base_0067_Data, NptTlsTrustAnchor_Base_0067_Size} /* Actalis Authentication Root CA */,
    { NptTlsTrustAnchor_Base_0068_Data, NptTlsTrustAnchor_Base_0068_Size} /* Trustis FPS Root CA */,
    { NptTlsTrustAnchor_Base_0069_Data, NptTlsTrustAnchor_Base_0069_Size} /* Buypass Class 2 Root CA */,
    { NptTlsTrustAnchor_Base_0070_Data, NptTlsTrustAnchor_Base_0070_Size} /* Buypass Class 3 Root CA */,
    { NptTlsTrustAnchor_Base_0071_Data, NptTlsTrustAnchor_Base_0071_Size} /* T-TeleSec GlobalRoot Class 3 */,
    { NptTlsTrustAnchor_Base_0072_Data, NptTlsTrustAnchor_Base_0072_Size} /* EE Certification Centre Root CA */,
    { NptTlsTrustAnchor_Base_0073_Data, NptTlsTrustAnchor_Base_0073_Size} /* D-TRUST Root Class 3 CA 2 2009 */,
    { NptTlsTrustAnchor_Base_0074_Data, NptTlsTrustAnchor_Base_0074_Size} /* D-TRUST Root Class 3 CA 2 EV 2009 */,
    { NptTlsTrustAnchor_Base_0075_Data, NptTlsTrustAnchor_Base_0075_Size} /* CA Disig Root R2 */,
    { NptTlsTrustAnchor_Base_0076_Data, NptTlsTrustAnchor_Base_0076_Size} /* ACCVRAIZ1 */,
    { NptTlsTrustAnchor_Base_0077_Data, NptTlsTrustAnchor_Base_0077_Size} /* TWCA Global Root CA */,
    { NptTlsTrustAnchor_Base_0078_Data, NptTlsTrustAnchor_Base_0078_Size} /* TeliaSonera Root CA v1 */,
    { NptTlsTrustAnchor_Base_0079_Data, NptTlsTrustAnchor_Base_0079_Size} /* E-Tugra Certification Authority */,
    { NptTlsTrustAnchor_Base_0080_Data, NptTlsTrustAnchor_Base_0080_Size} /* T-TeleSec GlobalRoot Class 2 */,
    { NptTlsTrustAnchor_Base_0081_Data, NptTlsTrustAnchor_Base_0081_Size} /* Atos TrustedRoot 2011 */,
    { NptTlsTrustAnchor_Base_0082_Data, NptTlsTrustAnchor_Base_0082_Size} /* QuoVadis Root CA 1 G3 */,
    { NptTlsTrustAnchor_Base_0083_Data, NptTlsTrustAnchor_Base_0083_Size} /* QuoVadis Root CA 2 G3 */,
    { NptTlsTrustAnchor_Base_0084_Data, NptTlsTrustAnchor_Base_0084_Size} /* QuoVadis Root CA 3 G3 */,
    { NptTlsTrustAnchor_Base_0085_Data, NptTlsTrustAnchor_Base_0085_Size} /* DigiCert Assured ID Root G2 */,
    { NptTlsTrustAnchor_Base_0086_Data, NptTlsTrustAnchor_Base_0086_Size} /* DigiCert Assured ID Root G3 */,
    { NptTlsTrustAnchor_Base_0087_Data, NptTlsTrustAnchor_Base_0087_Size} /* DigiCert Global Root G2 */,
    { NptTlsTrustAnchor_Base_0088_Data, NptTlsTrustAnchor_Base_0088_Size} /* DigiCert Global Root G3 */,
    { NptTlsTrustAnchor_Base_0089_Data, NptTlsTrustAnchor_Base_0089_Size} /* DigiCert Trusted Root G4 */,
    { NptTlsTrustAnchor_Base_0090_Data, NptTlsTrustAnchor_Base_0090_Size} /* COMODO RSA Certification Authority */,
    { NptTlsTrustAnchor_Base_0091_Data, NptTlsTrustAnchor_Base_0091_Size} /* USERTrust RSA Certification Authority */,
    { NptTlsTrustAnchor_Base_0092_Data, NptTlsTrustAnchor_Base_0092_Size} /* USERTrust ECC Certification Authority */,
    { NptTlsTrustAnchor_Base_0093_Data, NptTlsTrustAnchor_Base_0093_Size} /* GlobalSign ECC Root CA - R4 */,
    { NptTlsTrustAnchor_Base_0094_Data, NptTlsTrustAnchor_Base_0094_Size} /* GlobalSign ECC Root CA - R5 */,
    { NptTlsTrustAnchor_Base_0095_Data, NptTlsTrustAnchor_Base_0095_Size} /* Staat der Nederlanden Root CA - G3 */,
    { NptTlsTrustAnchor_Base_0096_Data, NptTlsTrustAnchor_Base_0096_Size} /* Staat der Nederlanden EV Root CA */,
    { NptTlsTrustAnchor_Base_0097_Data, NptTlsTrustAnchor_Base_0097_Size} /* IdenTrust Commercial Root CA 1 */,
    { NptTlsTrustAnchor_Base_0098_Data, NptTlsTrustAnchor_Base_0098_Size} /* IdenTrust Public Sector Root CA 1 */,
    { NptTlsTrustAnchor_Base_0099_Data, NptTlsTrustAnchor_Base_0099_Size} /* Entrust Root Certification Authority - G2 */,
    { NptTlsTrustAnchor_Base_0100_Data, NptTlsTrustAnchor_Base_0100_Size} /* Entrust Root Certification Authority - EC1 */,
    { NptTlsTrustAnchor_Base_0101_Data, NptTlsTrustAnchor_Base_0101_Size} /* CFCA EV ROOT */,
    { NptTlsTrustAnchor_Base_0102_Data, NptTlsTrustAnchor_Base_0102_Size} /* OISTE WISeKey Global Root GB CA */,
    { NptTlsTrustAnchor_Base_0103_Data, NptTlsTrustAnchor_Base_0103_Size} /* SZAFIR ROOT CA2 */,
    { NptTlsTrustAnchor_Base_0104_Data, NptTlsTrustAnchor_Base_0104_Size} /* Certum Trusted Network CA 2 */,
    { NptTlsTrustAnchor_Base_0105_Data, NptTlsTrustAnchor_Base_0105_Size} /* Hellenic Academic and Research Institutions RootCA 2015 */,
    { NptTlsTrustAnchor_Base_0106_Data, NptTlsTrustAnchor_Base_0106_Size} /* Hellenic Academic and Research Institutions ECC RootCA 2015 */,
    { NptTlsTrustAnchor_Base_0107_Data, NptTlsTrustAnchor_Base_0107_Size} /* ISRG Root X1 */,
    { NptTlsTrustAnchor_Base_0108_Data, NptTlsTrustAnchor_Base_0108_Size} /* AC RAIZ FNMT-RCM */,
    { NptTlsTrustAnchor_Base_0109_Data, NptTlsTrustAnchor_Base_0109_Size} /* Amazon Root CA 1 */,
    { NptTlsTrustAnchor_Base_0110_Data, NptTlsTrustAnchor_Base_0110_Size} /* Amazon Root CA 2 */,
    { NptTlsTrustAnchor_Base_0111_Data, NptTlsTrustAnchor_Base_0111_Size} /* Amazon Root CA 3 */,
    { NptTlsTrustAnchor_Base_0112_Data, NptTlsTrustAnchor_Base_0112_Size} /* Amazon Root CA 4 */,
    { NptTlsTrustAnchor_Base_0113_Data, NptTlsTrustAnchor_Base_0113_Size} /* LuxTrust Global Root 2 */,
    { NptTlsTrustAnchor_Base_0114_Data, NptTlsTrustAnchor_Base_0114_Size} /* TUBITAK Kamu SM SSL Kok Sertifikasi - Surum 1 */,
    { NptTlsTrustAnchor_Base_0115_Data, NptTlsTrustAnchor_Base_0115_Size} /* GDCA TrustAUTH R5 ROOT */,
    { NptTlsTrustAnchor_Base_0116_Data, NptTlsTrustAnchor_Base_0116_Size} /* TrustCor RootCert CA-1 */,
    { NptTlsTrustAnchor_Base_0117_Data, NptTlsTrustAnchor_Base_0117_Size} /* TrustCor RootCert CA-2 */,
    { NptTlsTrustAnchor_Base_0118_Data, NptTlsTrustAnchor_Base_0118_Size} /* TrustCor ECA-1 */,
    { NptTlsTrustAnchor_Base_0119_Data, NptTlsTrustAnchor_Base_0119_Size} /* SSL.com Root Certification Authority RSA */,
    { NptTlsTrustAnchor_Base_0120_Data, NptTlsTrustAnchor_Base_0120_Size} /* SSL.com Root Certification Authority ECC */,
    { NptTlsTrustAnchor_Base_0121_Data, NptTlsTrustAnchor_Base_0121_Size} /* SSL.com EV Root Certification Authority RSA R2 */,
    { NptTlsTrustAnchor_Base_0122_Data, NptTlsTrustAnchor_Base_0122_Size} /* SSL.com EV Root Certification Authority ECC */,
    { NptTlsTrustAnchor_Base_0123_Data, NptTlsTrustAnchor_Base_0123_Size} /* GlobalSign Root CA - R6 */,
    { NptTlsTrustAnchor_Base_0124_Data, NptTlsTrustAnchor_Base_0124_Size} /* OISTE WISeKey Global Root GC CA */,
    { NptTlsTrustAnchor_Base_0125_Data, NptTlsTrustAnchor_Base_0125_Size} /* GTS Root R1 */,
    { NptTlsTrustAnchor_Base_0126_Data, NptTlsTrustAnchor_Base_0126_Size} /* GTS Root R2 */,
    { NptTlsTrustAnchor_Base_0127_Data, NptTlsTrustAnchor_Base_0127_Size} /* GTS Root R3 */,
    { NptTlsTrustAnchor_Base_0128_Data, NptTlsTrustAnchor_Base_0128_Size} /* GTS Root R4 */,
    { NptTlsTrustAnchor_Base_0129_Data, NptTlsTrustAnchor_Base_0129_Size} /* UCA Global G2 Root */,
    { NptTlsTrustAnchor_Base_0130_Data, NptTlsTrustAnchor_Base_0130_Size} /* UCA Extended Validation Root */,
    { NptTlsTrustAnchor_Base_0131_Data, NptTlsTrustAnchor_Base_0131_Size} /* Certigna Root CA */,
    { NptTlsTrustAnchor_Base_0132_Data, NptTlsTrustAnchor_Base_0132_Size} /* emSign Root CA - G1 */,
    { NptTlsTrustAnchor_Base_0133_Data, NptTlsTrustAnchor_Base_0133_Size} /* emSign ECC Root CA - G3 */,
    { NptTlsTrustAnchor_Base_0134_Data, NptTlsTrustAnchor_Base_0134_Size} /* emSign Root CA - C1 */,
    { NptTlsTrustAnchor_Base_0135_Data, NptTlsTrustAnchor_Base_0135_Size} /* emSign ECC Root CA - C3 */,
    { NptTlsTrustAnchor_Base_0136_Data, NptTlsTrustAnchor_Base_0136_Size} /* Hongkong Post Root CA 3 */,
    { NptTlsTrustAnchor_Base_0137_Data, NptTlsTrustAnchor_Base_0137_Size} /* Entrust Root Certification Authority - G4 */,
    {0, 0} /* sentinel */
};
