/*****************************************************************
|
|   Neptune - Trust Anchors
|
|   This file is automatically generated by a script, do not edit!
|
| Copyright (c) 2002-2010, Axiomatic Systems, LLC.
| All rights reserved.
|
| Redistribution and use in source and binary forms, with or without
| modification, are permitted provided that the following conditions are met:
|     * Redistributions of source code must retain the above copyright
|       notice, this list of conditions and the following disclaimer.
|     * Redistributions in binary form must reproduce the above copyright
|       notice, this list of conditions and the following disclaimer in the
|       documentation and/or other materials provided with the distribution.
|     * Neither the name of Axiomatic Systems nor the
|       names of its contributors may be used to endorse or promote products
|       derived from this software without specific prior written permission.
|
| THIS SOFTWARE IS PROVIDED BY AXIOMATIC SYSTEMS ''AS IS'' AND ANY
| EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
| WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
| DISCLAIMED. IN NO EVENT SHALL AXIOMATIC SYSTEMS BE LIABLE FOR ANY
| DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
| (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
| LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND
| ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
| (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
| SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
|
 ****************************************************************/
 
 #include "NptTls.h"
 
 /* This file is automatically generated by GenTrustAnchorsTables.py, do not edit */

#include "NptTls.h"
const NPT_TlsTrustAnchorData NptTlsDefaultTrustAnchors[151] = {
    { NptTlsTrustAnchor_0000_Data, NptTlsTrustAnchor_0000_Size} /* Verisign/RSA Secure Server CA */,
    { NptTlsTrustAnchor_0001_Data, NptTlsTrustAnchor_0001_Size} /* GTE CyberTrust Root CA */,
    { NptTlsTrustAnchor_0002_Data, NptTlsTrustAnchor_0002_Size} /* GTE CyberTrust Global Root */,
    { NptTlsTrustAnchor_0003_Data, NptTlsTrustAnchor_0003_Size} /* Thawte Personal Basic CA */,
    { NptTlsTrustAnchor_0004_Data, NptTlsTrustAnchor_0004_Size} /* Thawte Personal Premium CA */,
    { NptTlsTrustAnchor_0005_Data, NptTlsTrustAnchor_0005_Size} /* Thawte Personal Freemail CA */,
    { NptTlsTrustAnchor_0006_Data, NptTlsTrustAnchor_0006_Size} /* Thawte Server CA */,
    { NptTlsTrustAnchor_0007_Data, NptTlsTrustAnchor_0007_Size} /* Thawte Premium Server CA */,
    { NptTlsTrustAnchor_0008_Data, NptTlsTrustAnchor_0008_Size} /* Equifax Secure CA */,
    { NptTlsTrustAnchor_0009_Data, NptTlsTrustAnchor_0009_Size} /* ABAecom (sub., Am. Bankers Assn.) Root CA */,
    { NptTlsTrustAnchor_0010_Data, NptTlsTrustAnchor_0010_Size} /* Digital Signature Trust Co. Global CA 1 */,
    { NptTlsTrustAnchor_0011_Data, NptTlsTrustAnchor_0011_Size} /* Digital Signature Trust Co. Global CA 3 */,
    { NptTlsTrustAnchor_0012_Data, NptTlsTrustAnchor_0012_Size} /* Digital Signature Trust Co. Global CA 2 */,
    { NptTlsTrustAnchor_0013_Data, NptTlsTrustAnchor_0013_Size} /* Digital Signature Trust Co. Global CA 4 */,
    { NptTlsTrustAnchor_0014_Data, NptTlsTrustAnchor_0014_Size} /* Verisign Class 1 Public Primary Certification Authority */,
    { NptTlsTrustAnchor_0015_Data, NptTlsTrustAnchor_0015_Size} /* Verisign Class 2 Public Primary Certification Authority */,
    { NptTlsTrustAnchor_0016_Data, NptTlsTrustAnchor_0016_Size} /* Verisign Class 3 Public Primary Certification Authority */,
    { NptTlsTrustAnchor_0017_Data, NptTlsTrustAnchor_0017_Size} /* Verisign Class 1 Public Primary Certification Authority - G2 */,
    { NptTlsTrustAnchor_0018_Data, NptTlsTrustAnchor_0018_Size} /* Verisign Class 2 Public Primary Certification Authority - G2 */,
    { NptTlsTrustAnchor_0019_Data, NptTlsTrustAnchor_0019_Size} /* Verisign Class 3 Public Primary Certification Authority - G2 */,
    { NptTlsTrustAnchor_0020_Data, NptTlsTrustAnchor_0020_Size} /* Verisign Class 4 Public Primary Certification Authority - G2 */,
    { NptTlsTrustAnchor_0021_Data, NptTlsTrustAnchor_0021_Size} /* GlobalSign Root CA */,
    { NptTlsTrustAnchor_0022_Data, NptTlsTrustAnchor_0022_Size} /* GlobalSign Root CA - R2 */,
    { NptTlsTrustAnchor_0023_Data, NptTlsTrustAnchor_0023_Size} /* ValiCert Class 1 VA */,
    { NptTlsTrustAnchor_0024_Data, NptTlsTrustAnchor_0024_Size} /* ValiCert Class 2 VA */,
    { NptTlsTrustAnchor_0025_Data, NptTlsTrustAnchor_0025_Size} /* RSA Root Certificate 1 */,
    { NptTlsTrustAnchor_0026_Data, NptTlsTrustAnchor_0026_Size} /* Verisign Class 1 Public Primary Certification Authority - G3 */,
    { NptTlsTrustAnchor_0027_Data, NptTlsTrustAnchor_0027_Size} /* Verisign Class 2 Public Primary Certification Authority - G3 */,
    { NptTlsTrustAnchor_0028_Data, NptTlsTrustAnchor_0028_Size} /* Verisign Class 3 Public Primary Certification Authority - G3 */,
    { NptTlsTrustAnchor_0029_Data, NptTlsTrustAnchor_0029_Size} /* Verisign Class 4 Public Primary Certification Authority - G3 */,
    { NptTlsTrustAnchor_0030_Data, NptTlsTrustAnchor_0030_Size} /* Entrust.net Secure Server CA */,
    { NptTlsTrustAnchor_0031_Data, NptTlsTrustAnchor_0031_Size} /* Entrust.net Secure Personal CA */,
    { NptTlsTrustAnchor_0032_Data, NptTlsTrustAnchor_0032_Size} /* Entrust.net Premium 2048 Secure Server CA */,
    { NptTlsTrustAnchor_0033_Data, NptTlsTrustAnchor_0033_Size} /* Baltimore CyberTrust Root */,
    { NptTlsTrustAnchor_0034_Data, NptTlsTrustAnchor_0034_Size} /* Equifax Secure Global eBusiness CA */,
    { NptTlsTrustAnchor_0035_Data, NptTlsTrustAnchor_0035_Size} /* Equifax Secure eBusiness CA 1 */,
    { NptTlsTrustAnchor_0036_Data, NptTlsTrustAnchor_0036_Size} /* Equifax Secure eBusiness CA 2 */,
    { NptTlsTrustAnchor_0037_Data, NptTlsTrustAnchor_0037_Size} /* Visa International Global Root 2 */,
    { NptTlsTrustAnchor_0038_Data, NptTlsTrustAnchor_0038_Size} /* beTRUSTed Root CA */,
    { NptTlsTrustAnchor_0039_Data, NptTlsTrustAnchor_0039_Size} /* AddTrust Low-Value Services Root */,
    { NptTlsTrustAnchor_0040_Data, NptTlsTrustAnchor_0040_Size} /* AddTrust External Root */,
    { NptTlsTrustAnchor_0041_Data, NptTlsTrustAnchor_0041_Size} /* AddTrust Public Services Root */,
    { NptTlsTrustAnchor_0042_Data, NptTlsTrustAnchor_0042_Size} /* AddTrust Qualified Certificates Root */,
    { NptTlsTrustAnchor_0043_Data, NptTlsTrustAnchor_0043_Size} /* Verisign Time Stamping Authority CA */,
    { NptTlsTrustAnchor_0044_Data, NptTlsTrustAnchor_0044_Size} /* Thawte Time Stamping CA */,
    { NptTlsTrustAnchor_0045_Data, NptTlsTrustAnchor_0045_Size} /* Entrust.net Global Secure Server CA */,
    { NptTlsTrustAnchor_0046_Data, NptTlsTrustAnchor_0046_Size} /* Entrust.net Global Secure Personal CA */,
    { NptTlsTrustAnchor_0047_Data, NptTlsTrustAnchor_0047_Size} /* Entrust Root Certification Authority */,
    { NptTlsTrustAnchor_0048_Data, NptTlsTrustAnchor_0048_Size} /* AOL Time Warner Root Certification Authority 1 */,
    { NptTlsTrustAnchor_0049_Data, NptTlsTrustAnchor_0049_Size} /* AOL Time Warner Root Certification Authority 2 */,
    { NptTlsTrustAnchor_0050_Data, NptTlsTrustAnchor_0050_Size} /* beTRUSTed Root CA-Baltimore Implementation */,
    { NptTlsTrustAnchor_0051_Data, NptTlsTrustAnchor_0051_Size} /* beTRUSTed Root CA - Entrust Implementation */,
    { NptTlsTrustAnchor_0052_Data, NptTlsTrustAnchor_0052_Size} /* beTRUSTed Root CA - RSA Implementation */,
    { NptTlsTrustAnchor_0053_Data, NptTlsTrustAnchor_0053_Size} /* RSA Security 2048 v3 */,
    { NptTlsTrustAnchor_0054_Data, NptTlsTrustAnchor_0054_Size} /* RSA Security 1024 v3 */,
    { NptTlsTrustAnchor_0055_Data, NptTlsTrustAnchor_0055_Size} /* GeoTrust Global CA */,
    { NptTlsTrustAnchor_0056_Data, NptTlsTrustAnchor_0056_Size} /* GeoTrust Global CA 2 */,
    { NptTlsTrustAnchor_0057_Data, NptTlsTrustAnchor_0057_Size} /* GeoTrust Universal CA */,
    { NptTlsTrustAnchor_0058_Data, NptTlsTrustAnchor_0058_Size} /* GeoTrust Universal CA 2 */,
    { NptTlsTrustAnchor_0059_Data, NptTlsTrustAnchor_0059_Size} /* UTN-USER First-Network Applications */,
    { NptTlsTrustAnchor_0060_Data, NptTlsTrustAnchor_0060_Size} /* America Online Root Certification Authority 1 */,
    { NptTlsTrustAnchor_0061_Data, NptTlsTrustAnchor_0061_Size} /* America Online Root Certification Authority 2 */,
    { NptTlsTrustAnchor_0062_Data, NptTlsTrustAnchor_0062_Size} /* Visa eCommerce Root */,
    { NptTlsTrustAnchor_0063_Data, NptTlsTrustAnchor_0063_Size} /* TC TrustCenter, Germany, Class 2 CA */,
    { NptTlsTrustAnchor_0064_Data, NptTlsTrustAnchor_0064_Size} /* TC TrustCenter, Germany, Class 3 CA */,
    { NptTlsTrustAnchor_0065_Data, NptTlsTrustAnchor_0065_Size} /* Certum Root CA */,
    { NptTlsTrustAnchor_0066_Data, NptTlsTrustAnchor_0066_Size} /* Comodo AAA Services root */,
    { NptTlsTrustAnchor_0067_Data, NptTlsTrustAnchor_0067_Size} /* Comodo Secure Services root */,
    { NptTlsTrustAnchor_0068_Data, NptTlsTrustAnchor_0068_Size} /* Comodo Trusted Services root */,
    { NptTlsTrustAnchor_0069_Data, NptTlsTrustAnchor_0069_Size} /* IPS Chained CAs root */,
    { NptTlsTrustAnchor_0070_Data, NptTlsTrustAnchor_0070_Size} /* IPS CLASE1 root */,
    { NptTlsTrustAnchor_0071_Data, NptTlsTrustAnchor_0071_Size} /* IPS CLASE3 root */,
    { NptTlsTrustAnchor_0072_Data, NptTlsTrustAnchor_0072_Size} /* IPS CLASEA1 root */,
    { NptTlsTrustAnchor_0073_Data, NptTlsTrustAnchor_0073_Size} /* IPS CLASEA3 root */,
    { NptTlsTrustAnchor_0074_Data, NptTlsTrustAnchor_0074_Size} /* IPS Servidores root */,
    { NptTlsTrustAnchor_0075_Data, NptTlsTrustAnchor_0075_Size} /* IPS Timestamping root */,
    { NptTlsTrustAnchor_0076_Data, NptTlsTrustAnchor_0076_Size} /* QuoVadis Root CA */,
    { NptTlsTrustAnchor_0077_Data, NptTlsTrustAnchor_0077_Size} /* QuoVadis Root CA 2 */,
    { NptTlsTrustAnchor_0078_Data, NptTlsTrustAnchor_0078_Size} /* QuoVadis Root CA 3 */,
    { NptTlsTrustAnchor_0079_Data, NptTlsTrustAnchor_0079_Size} /* Security Communication Root CA */,
    { NptTlsTrustAnchor_0080_Data, NptTlsTrustAnchor_0080_Size} /* Sonera Class 1 Root CA */,
    { NptTlsTrustAnchor_0081_Data, NptTlsTrustAnchor_0081_Size} /* Sonera Class 2 Root CA */,
    { NptTlsTrustAnchor_0082_Data, NptTlsTrustAnchor_0082_Size} /* Staat der Nederlanden Root CA */,
    { NptTlsTrustAnchor_0083_Data, NptTlsTrustAnchor_0083_Size} /* TDC Internet Root CA */,
    { NptTlsTrustAnchor_0084_Data, NptTlsTrustAnchor_0084_Size} /* TDC OCES Root CA */,
    { NptTlsTrustAnchor_0085_Data, NptTlsTrustAnchor_0085_Size} /* UTN DATACorp SGC Root CA */,
    { NptTlsTrustAnchor_0086_Data, NptTlsTrustAnchor_0086_Size} /* UTN USERFirst Email Root CA */,
    { NptTlsTrustAnchor_0087_Data, NptTlsTrustAnchor_0087_Size} /* UTN USERFirst Hardware Root CA */,
    { NptTlsTrustAnchor_0088_Data, NptTlsTrustAnchor_0088_Size} /* UTN USERFirst Object Root CA */,
    { NptTlsTrustAnchor_0089_Data, NptTlsTrustAnchor_0089_Size} /* Camerfirma Chambers of Commerce Root */,
    { NptTlsTrustAnchor_0090_Data, NptTlsTrustAnchor_0090_Size} /* Camerfirma Global Chambersign Root */,
    { NptTlsTrustAnchor_0091_Data, NptTlsTrustAnchor_0091_Size} /* NetLock Qualified (Class QA) Root */,
    { NptTlsTrustAnchor_0092_Data, NptTlsTrustAnchor_0092_Size} /* NetLock Notary (Class A) Root */,
    { NptTlsTrustAnchor_0093_Data, NptTlsTrustAnchor_0093_Size} /* NetLock Business (Class B) Root */,
    { NptTlsTrustAnchor_0094_Data, NptTlsTrustAnchor_0094_Size} /* NetLock Express (Class C) Root */,
    { NptTlsTrustAnchor_0095_Data, NptTlsTrustAnchor_0095_Size} /* XRamp Global CA Root */,
    { NptTlsTrustAnchor_0096_Data, NptTlsTrustAnchor_0096_Size} /* Go Daddy Class 2 CA */,
    { NptTlsTrustAnchor_0097_Data, NptTlsTrustAnchor_0097_Size} /* Starfield Class 2 CA */,
    { NptTlsTrustAnchor_0098_Data, NptTlsTrustAnchor_0098_Size} /* StartCom Ltd. */,
    { NptTlsTrustAnchor_0099_Data, NptTlsTrustAnchor_0099_Size} /* StartCom Certification Authority */,
    { NptTlsTrustAnchor_0100_Data, NptTlsTrustAnchor_0100_Size} /* Taiwan GRCA */,
    { NptTlsTrustAnchor_0101_Data, NptTlsTrustAnchor_0101_Size} /* Firmaprofesional Root CA */,
    { NptTlsTrustAnchor_0102_Data, NptTlsTrustAnchor_0102_Size} /* Wells Fargo Root CA */,
    { NptTlsTrustAnchor_0103_Data, NptTlsTrustAnchor_0103_Size} /* Swisscom Root CA 1 */,
    { NptTlsTrustAnchor_0104_Data, NptTlsTrustAnchor_0104_Size} /* DigiCert Assured ID Root CA */,
    { NptTlsTrustAnchor_0105_Data, NptTlsTrustAnchor_0105_Size} /* DigiCert Global Root CA */,
    { NptTlsTrustAnchor_0106_Data, NptTlsTrustAnchor_0106_Size} /* DigiCert High Assurance EV Root CA */,
    { NptTlsTrustAnchor_0107_Data, NptTlsTrustAnchor_0107_Size} /* Certplus Class 2 Primary CA */,
    { NptTlsTrustAnchor_0108_Data, NptTlsTrustAnchor_0108_Size} /* DST Root CA X3 */,
    { NptTlsTrustAnchor_0109_Data, NptTlsTrustAnchor_0109_Size} /* DST ACES CA X6 */,
    { NptTlsTrustAnchor_0110_Data, NptTlsTrustAnchor_0110_Size} /* TURKTRUST Certificate Services Provider Root 1 */,
    { NptTlsTrustAnchor_0111_Data, NptTlsTrustAnchor_0111_Size} /* TURKTRUST Certificate Services Provider Root 2 */,
    { NptTlsTrustAnchor_0112_Data, NptTlsTrustAnchor_0112_Size} /* SwissSign Platinum CA - G2 */,
    { NptTlsTrustAnchor_0113_Data, NptTlsTrustAnchor_0113_Size} /* SwissSign Gold CA - G2 */,
    { NptTlsTrustAnchor_0114_Data, NptTlsTrustAnchor_0114_Size} /* SwissSign Silver CA - G2 */,
    { NptTlsTrustAnchor_0115_Data, NptTlsTrustAnchor_0115_Size} /* GeoTrust Primary Certification Authority */,
    { NptTlsTrustAnchor_0116_Data, NptTlsTrustAnchor_0116_Size} /* thawte Primary Root CA */,
    { NptTlsTrustAnchor_0117_Data, NptTlsTrustAnchor_0117_Size} /* VeriSign Class 3 Public Primary Certification Authority - G5 */,
    { NptTlsTrustAnchor_0118_Data, NptTlsTrustAnchor_0118_Size} /* SecureTrust CA */,
    { NptTlsTrustAnchor_0119_Data, NptTlsTrustAnchor_0119_Size} /* Secure Global CA */,
    { NptTlsTrustAnchor_0120_Data, NptTlsTrustAnchor_0120_Size} /* COMODO Certification Authority */,
    { NptTlsTrustAnchor_0121_Data, NptTlsTrustAnchor_0121_Size} /* DigiNotar Root CA */,
    { NptTlsTrustAnchor_0122_Data, NptTlsTrustAnchor_0122_Size} /* Network Solutions Certificate Authority */,
    { NptTlsTrustAnchor_0123_Data, NptTlsTrustAnchor_0123_Size} /* WellsSecure Public Root Certificate Authority */,
    { NptTlsTrustAnchor_0124_Data, NptTlsTrustAnchor_0124_Size} /* COMODO ECC Certification Authority */,
    { NptTlsTrustAnchor_0125_Data, NptTlsTrustAnchor_0125_Size} /* IGC/A */,
    { NptTlsTrustAnchor_0126_Data, NptTlsTrustAnchor_0126_Size} /* Security Communication EV RootCA1 */,
    { NptTlsTrustAnchor_0127_Data, NptTlsTrustAnchor_0127_Size} /* OISTE WISeKey Global Root GA CA */,
    { NptTlsTrustAnchor_0128_Data, NptTlsTrustAnchor_0128_Size} /* S-TRUST Authentication and Encryption Root CA 2005 PN */,
    { NptTlsTrustAnchor_0129_Data, NptTlsTrustAnchor_0129_Size} /* Microsec e-Szigno Root CA */,
    { NptTlsTrustAnchor_0130_Data, NptTlsTrustAnchor_0130_Size} /* Certigna */,
    { NptTlsTrustAnchor_0131_Data, NptTlsTrustAnchor_0131_Size} /* AC Ra\xC3\xADz Certic\xC3\xA1mara S.A. */,
    { NptTlsTrustAnchor_0132_Data, NptTlsTrustAnchor_0132_Size} /* TC TrustCenter Class 2 CA II */,
    { NptTlsTrustAnchor_0133_Data, NptTlsTrustAnchor_0133_Size} /* TC TrustCenter Class 3 CA II */,
    { NptTlsTrustAnchor_0134_Data, NptTlsTrustAnchor_0134_Size} /* TC TrustCenter Universal CA I */,
    { NptTlsTrustAnchor_0135_Data, NptTlsTrustAnchor_0135_Size} /* Deutsche Telekom Root CA 2 */,
    { NptTlsTrustAnchor_0136_Data, NptTlsTrustAnchor_0136_Size} /* ComSign CA */,
    { NptTlsTrustAnchor_0137_Data, NptTlsTrustAnchor_0137_Size} /* ComSign Secured CA */,
    { NptTlsTrustAnchor_0138_Data, NptTlsTrustAnchor_0138_Size} /* Cybertrust Global Root */,
    { NptTlsTrustAnchor_0139_Data, NptTlsTrustAnchor_0139_Size} /* ePKI Root Certification Authority */,
    { NptTlsTrustAnchor_0140_Data, NptTlsTrustAnchor_0140_Size} /* T\xc3\x9c\x42\xC4\xB0TAK UEKAE K\xC3\xB6k Sertifika Hizmet Sa\xC4\x9Flay\xc4\xb1\x63\xc4\xb1s\xc4\xb1 - S\xC3\xBCr\xC3\xBCm 3 */,
    { NptTlsTrustAnchor_0141_Data, NptTlsTrustAnchor_0141_Size} /* Buypass Class 2 CA 1 */,
    { NptTlsTrustAnchor_0142_Data, NptTlsTrustAnchor_0142_Size} /* Buypass Class 3 CA 1 */,
    { NptTlsTrustAnchor_0143_Data, NptTlsTrustAnchor_0143_Size} /* EBG Elektronik Sertifika Hizmet Sa\xC4\x9Flay\xc4\xb1\x63\xc4\xb1s\xc4\xb1 */,
    { NptTlsTrustAnchor_0144_Data, NptTlsTrustAnchor_0144_Size} /* certSIGN ROOT CA */,
    { NptTlsTrustAnchor_0145_Data, NptTlsTrustAnchor_0145_Size} /* CNNIC ROOT */,
    { NptTlsTrustAnchor_0146_Data, NptTlsTrustAnchor_0146_Size} /* ApplicationCA - Japanese Government */,
    { NptTlsTrustAnchor_0147_Data, NptTlsTrustAnchor_0147_Size} /* GeoTrust Primary Certification Authority - G3 */,
    { NptTlsTrustAnchor_0148_Data, NptTlsTrustAnchor_0148_Size} /* thawte Primary Root CA - G2 */,
    { NptTlsTrustAnchor_0149_Data, NptTlsTrustAnchor_0149_Size} /* GeoTrust Primary Certification Authority - G2 */,
    {0, 0} /* sentinel */
};
